"""empty message

Revision ID: 2356505397aa
Revises: ec95dbb8ed97
Create Date: 2022-01-08 22:33:48.733809

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2356505397aa'
down_revision = 'ec95dbb8ed97'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'subject', ['name'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'subject', type_='unique')
    # ### end Alembic commands ###
